### ISSUE TITLE
Merging into a file without overwriting its content

### ISSUE THREAD

**Issue by kipz** [atomist/rug-resolver#9]
_From @Lawouach on November 4, 2016 8:39_

As it stands, `merge` will overwrite the content of a file with whatever the mustache/velocity template contains. We should have something that blens `merge` and `append` at the same time.

_Copied from original issue: atomist-recycling/rug-lib#71_

**Comment by cdupuis** [comment]
@kipz, should that belong here?

**Comment by kipz** [comment]
This issue was moved to atomist/rug#103
